src/main/java/br/com/dbserver/dbconsultorias/companies/CompanyMB.java
package br.com.dbserver.dbconsultorias.companies;

import java.io.IOException;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.faces.bean.RequestScoped;
import javax.inject.Inject;

import br.com.dbserver.dbconsultorias.users.User;

@ManagedBean
@RequestScoped
public class CompanyMB {
	
    @Inject
    private CompanyRepository companyRepository;
    
    private Long id;
    private String name;
    private String address;
    private String phone;
    private String cnpj;
    private String cep;
    private String city;
    private String msg;

    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    public String getCnpj() {
        return cnpj;
    }

    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    
    public String getCep() {
        return cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @PostConstruct
    public void initialize() {
    }

    public List<Company> getAll() {
        return companyRepository.findAll();
    }

    public void removeUserFromCompany(Company c, User u) {
        companyRepository.removeUserFromCompany(c, u);
    }
    
    public void removeCompany(Company c) {
        if(c.getListUsers().isEmpty()){
            companyRepository.remove(c);
            
        }else{
           
        }
    }

    public void save() throws IOException {
        Company entity = new Company(getName(), getCnpj(), getPhone(), getAddress(), getCep(), getCity());
        companyRepository.create(entity);
        String url = "createContact.xhtml?companyid="+entity.getId(); 
        FacesContext.getCurrentInstance().getExternalContext().redirect(url);
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

}

src/main/java/br/com/dbserver/dbconsultorias/index/IndexMB.java
package br.com.dbserver.dbconsultorias.index;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import br.com.dbserver.dbconsultorias.login.UserSession;

@ManagedBean
@ViewScoped
public class IndexMB {

    private String page;

    @ManagedProperty(value = "#{userSession}")
    private UserSession userSession;

    public void setUserSession(UserSession userSession) {
        this.userSession = userSession;
    }

    @PostConstruct
    public void init() {
    	page = "listcompany/listcompany"; // Default include.
    }

    public String getPage() {
        return page;
    }

    public void setPage(String page) {
        this.page = page;
    }

    public UserSession getUserSession() {
        return userSession;
    }

}

src/main/java/br/com/dbserver/dbconsultorias/users/UserListMB.java
package br.com.dbserver.dbconsultorias.users;

import java.util.List;


import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;



@ManagedBean
@SessionScoped
public class UserListMB {

    private UserRepository userRepository;
    private List<User> users;

    @Inject
    public void setUserRepository(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    public List<User> getUsers() {
        return users;
    }

}

src/main/java/br/com/dbserver/dbconsultorias/users/UserMB.java
package br.com.dbserver.dbconsultorias.users;

import java.util.List;

import javax.enterprise.context.RequestScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.inject.Inject;

import br.com.dbserver.dbconsultorias.companies.CompanyRepository;
import br.com.dbserver.dbconsultorias.roles.Role;

@ManagedBean
public class UserMB {
    
    @Inject
    private UserRepository repository;

    @Inject
    private CompanyRepository companyRepository;

    private String name;
    private String email;
    private String phone;
    private String username;

    private Long companyid;

    public Long getCompanyid() {
        return companyid;
    }
   
    public void setCompanyid(Long companyid) {
        this.companyid = companyid;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    
    public String getUsername() {
        return username;
    }

    public String getPhone() {
        return phone;
    }
    
    public String getName() {
        return name;
    }

    public String getEmail() {
        return email;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    
    public void createCustomer(){
        User user = new User();
        /*String companyids = FacesContext.getCurrentInstance().
                getExternalContext().getRequestParameterMap().get("companyid");*/
        System.out.println(getCompanyid());
        /*Company company = companyRepository.find(companyids);
        user.setCompany(company);
        user.setUsername(username);
        user.setName(name);
        user.setPhone(phone);
        user.setEmail(email);
        user.setPassword(new Encrypter().randomString(10));
        user.setRole(repository.findRole("cliente"));
        repository.create(user);*/
    }
    
    
    public List<User> getUsersByCompanyId() {
        return companyRepository.find(new Long(9999)).getListUsers();
    }
    
    public List<User> getAll() {
        return repository.findAll();
    }

    public List<Role> getAllRoles() {
        return repository.getAllRoles();
    }
}

src/main/webapp/WEB-INF/templates/footer.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
	<ui:composition>
	</ui:composition>
</h:body>
</html>

src/main/webapp/WEB-INF/templates/header.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
	<ui:composition>
	</ui:composition>
</h:body>
</html>

src/main/webapp/WEB-INF/templates/menu.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
	<ui:composition>
			<h:outputStylesheet library="css" name="tableStyle.css" />
			<nav>
				<div class="nav-wrapper">
					<h:form>
						<ul id="nav" class="right hide-on-med-and-down">
							<li><h:link value="Lista de Clientes"
									outcome="/listcompany/listcompany" /></li>
							<li><h:link value="Cadastro de Clientes" outcome="/customer/createCustomer" /></li>
						</ul>
					</h:form>
				</div>
			</nav>
	</ui:composition>
</h:body>
</html>

src/main/webapp/WEB-INF/templates/template.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<script
		src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<link rel="stylesheet"
		href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css"></link>
	<link rel="stylesheet"
		href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"></link>
	<script
		src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
		rel="stylesheet" />
	<title><ui:insert name="title">DBConsultorias</ui:insert></title>
</h:head>
<h:body>
	<div id="header">
		<ui:insert name="header">
			<ui:include src="header.xhtml" />
		</ui:insert>
	</div>
	<ui:include src="menu.xhtml" />
	<div id="content">
		<ui:insert name="content" />
	</div>
	<div id="footer">
		<ui:insert name="footer">
			<ui:include src="footer.xhtml" />
		</ui:insert>
	</div>
</h:body>
</html>

src/main/webapp/customer/createContact.xhtml
<ui:composition template="/WEB-INF/templates/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
	<ui:define name="content">
		<h:outputStylesheet library="css" name="default.css" />
		<h:outputStylesheet library="css" name="materialize-override.css" />
		<div class="container">
			<div class="row">
				<div class="col s12 m12 l12">
					<div class="row">
						<div class="input-field col s12 m12 l12">
							<span class="title-lg db-color">Adicionar contatos</span>
						</div>
					</div>
					<h:form class="padding-bottom">

						<div class="row">
							<h:inputHidden id="companyid" value="1" />

							<div class="input-field col s12 m4 l4">
								<h:inputText id="username" class="validate"
									value="#{userMB.username}" pt:placeholder="Somente letras" />
								<h:outputLabel for="username" value="Username" />
							</div>

							<div class="input-field col s12 m4 l4">
								<h:inputText id="email" class="validate" value="#{userMB.email}" />
								<h:outputLabel for="email" value="E-mail" />
							</div>

							<div class="input-field col s12 m4 l4">
								<h:inputText id="phone" class="validate" value="#{userMB.phone}" />
								<h:outputLabel for="phone" value="Telefone" />
							</div>
						</div>

						<div class="row">
							<div class="input-field col s12 m12 l12">
								<h:inputText id="name" class="validate" value="#{userMB.name}" />
								<h:outputLabel for="name" value="Nome do contato" />
							</div>
						</div>

						<div class="input-field col s12 m12 l12">
							<h:commandButton
								styleClass="btn waves-effect waves-light right btn-db"
								action="#{userMB.createCustomer}" value="Adicionar" ajax="false">
							</h:commandButton>
						</div>

					</h:form>
					<div class="row">
						<div class="col s12 m12 l12">
							<table class="highlight bordered responsive-table">
								<thead>
									<tr>
										<th data-field="username">Username</th>
										<th data-field="name">Nome</th>
										<th data-field="phone">Telefone</th>
										<th data-field="email">E-mail</th>
										<th class="center-align" data-field="price">Ações</th>
									</tr>
								</thead>

								<tbody>
									<ui:repeat value="#{userMB.usersByCompanyId}" var="user">
										<tr>
											<td><h:outputText value="#{user.username}" /></td>
											<td><h:outputText value="#{user.name}" /></td>
											<td><h:outputText value="#{user.phone}" /></td>
											<td><h:outputText value="#{user.email}" /></td>
											<td class="center-align"><a
												class="blue-text margin-right" href="#"
												title="Editar contato">
												
												<i class="fa fa-edit" aria-hidden="true"></i>
												
												</a> <a class="red-text" href="#"
												title="Excluir contato"><i class="fa fa-trash"
													aria-hidden="true"></i></a></td>
										</tr>
									</ui:repeat>
								</tbody>
							</table>
						</div>
					</div>

				</div>
			</div>
		</div>
	</ui:define>
</ui:composition>

src/main/webapp/customer/createCustomer.xhtml
<ui:composition template="/WEB-INF/templates/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
	<ui:define name="content">
		<h:outputStylesheet library="css" name="default.css" />
		<h:outputStylesheet library="css" name="materialize-override.css" />
		<div class="container">
			<div class="row">
				<div class="col s12 m12 l12">
					<div class="row">
						<div class="input-field col s12 m12 l12">
							<span class="title-lg db-color">Cadastro de Cliente</span>
						</div>
					</div>
					<h:form styleClass="padding-bottom">
						<div class="row">
							<div class="input-field col s12">
								<h:inputText id="name" class="validate"
									value="#{companyMB.name}" />
								<h:outputLabel for="name" value="Nome do cliente" />
							</div>
						</div>
						<div class="row">
							<div class="input-field col s6">
								<h:inputText id="cnpj" class="validate"
									value="#{companyMB.cnpj}" />
								<h:outputLabel for="cnpj" value="CNPJ" />
							</div>
							<div class="input-field col s6">
								<h:inputText id="phone" class="validate"
									value="#{companyMB.phone}" />
								<h:outputLabel for="phone" value="Telefone" />
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<h:inputText id="address" class="validate"
									value="#{companyMB.address}" />
								<h:outputLabel for="address" value="Endereço" />
							</div>
						</div>
						<div class="row">
							<div class="input-field col s6">
								<h:inputText id="cep" class="validate"
									value="#{companyMB.cep}" />
								<h:outputLabel for="cep" value="CEP" />
							</div>
							<div class="input-field col s6">
								<h:inputText id="city" class="validate"
									value="#{companyMB.city}" />
								<h:outputLabel for="city" value="Cidade" />
							</div>
						</div>

						<div class="input-field col s12 m12 l12">
							<h:commandButton styleClass="btn waves-effect waves-light right btn-db"
								action="#{companyMB.save}" value="Salvar" ajax="false">
							</h:commandButton>
						</div>
					</h:form>
				</div>
			</div>
		</div>
	</ui:define>
</ui:composition>

src/main/webapp/index.xhtml
<ui:composition template="WEB-INF/templates/template.xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
	<ui:define name="content">
		<!-- Default page -->
		Bem Vindo
	</ui:define>
</ui:composition>

src/main/webapp/listcompany/listcompany.xhtml
<ui:composition template="/WEB-INF/templates/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui">
	<ui:define name="content">
		<h:outputStylesheet library="css" name="tableStyle.css" />
		<h:outputScript library="js" name="functions.js" />

		<div class="row">
			<br></br>
			<div class="row">
				<div class="col s3 center-align">
					<h6>Clientes</h6>
				</div>
				<div class="col s2 center-align">
					<h6>CNPJ</h6>
				</div>
				<div class="col s2 center-align">
					<h6>Telefone</h6>
				</div>
				<div class="col s3 center-align">
					<h6>Local</h6>
				</div>
				<div class="col s2">
					<br></br>
				</div>
			</div>
			<div class="divider"></div>
			<br></br>
			<h:form>
				<ui:repeat value="#{companyMB.all}" var="company">
					<div>
						<div class="col s3 center-align">
							<h:outputText value="#{company.name}" />
						</div>
						<div class="col s2 center-align">
							<h:outputText value="#{company.cnpj}" />
						</div>
						<div class="col s2 center-align">
							<h:outputText value="#{company.phone}" />
						</div>
						<div class="col s3 center-align">
							<h:outputText value="#{company.address}, " />
							<h:outputText value="#{company.city}, " />
							<h:outputText value="#{company.cep}" />
						</div>
						<div class="col s1 center-align">
							<h:commandButton action="#{companyMB.removeCompany(company)}"
								image="/resources/img/remove.png" style="width:20px;"
								ajax="false" />
						</div>
						<div class="col s1 center-align">
							<h:graphicImage id="expand" value="/resources/img/down.png"
								onclick="toggleDetails(this);" width="20" height="20" />
						</div>
					</div>
					<div class="row">
						<div align="center">
							<h:outputText class="teste"
								value="Não há dados para serem exibidos!"
								rendered="#{empty companyMB.all}" />
						</div>
						<div class="col s12 highlight empresacomborda">
							<div class="col s1">
								<br></br>
							</div>
							<div class="col s7 backgroundgray">
								<h:dataTable id="details" value="#{company.listUsers}"
									var="user" style="display: none;">
									<f:facet name="header" class="contact"> Contatos:</f:facet>
									<h:column>
										<f:facet name="header">Username</f:facet>
										<h:outputText value="#{user.username}" />
									</h:column>
									<h:column>
										<f:facet name="header">Nome</f:facet>
										<h:outputText value="#{user.name}" />
									</h:column>
									<h:column>
										<f:facet name="header">Telefone</f:facet>
										<h:outputText value="#{user.phone}" />
									</h:column>
									<h:column>
										<f:facet name="header">Email</f:facet>
										<h:outputText value="#{user.email}" />
									</h:column>
									<h:column>
										<h:panelGroup style="display:block; text-align:right">
											<h:commandButton
												action="#{companyMB.removeUserFromCompany(company,user)}"
												image="/resources/img/remove.png" style="width:20px;" />
										</h:panelGroup>
									</h:column>
								</h:dataTable>
							</div>
						</div>
					</div>
				</ui:repeat>
			</h:form>
		</div>

	</ui:define>
</ui:composition>

src/main/webapp/login/login.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:head>

	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<link rel="stylesheet"
		href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css"></link>
	<script
		src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>

	<title>Login</title>
</h:head>
<h:body style="background-color: #f5f5f5;">
	<div class="corpo"
		style="margin-top: 125px; margin-left: auto; margin-right: auto; background-color: #fff; width: 400px; height: 450px; border-radius: 10px;">
		<div class="logo"
			style="padding-top: 20px; margin-left: 22%; margin-right: auto;">
			<img src="http://www.dbserver.com.br/images/LogoDB.png"
				alt="Logo dbServer" width="210" />

		</div>


		<div class="login" style="margin-bottom: 10px; width: 350px;">
			<h:form id="register">

				<h:message for="RegisterGroupPanel" style="color:red;" />

				<h:panelGrid columns="3" id="RegisterGroupPanel">

					<h:outputLabel for="username" value="Usuário : " />
					<h:inputText id="username" value="#{loginMB.username}"
						pt:placeholder="Digite seu usário." required="true"
						requiredMessage="Digite o usuário." />
					<h:messages for="username" style="color: red;"/>

					<h:outputLabel for="password" value="Senha : " />
					<h:inputSecret id="password" maxlength="6"
						value="#{loginMB.password}" pt:placeholder="Digite sua Senha."
						required="true" requiredMessage="Digite a senha.">
						<f:attribute name="confirmPassword" value="#{confirmPassword}" />
					</h:inputSecret>
					<h:message for="password" style="color: red;"/>
					

				</h:panelGrid>
				
				<!--  <div class="msgDeErro" align="center" style="margin-top: 0px;" >
				<h:messages globalOnly="true" style="color: red"/>
				</div>-->
				
				
				<div class="botao" align="center" style="margin-top: 5px;">
					<h:messages globalOnly="true" style="color: red"/>
					<h:commandButton class="btn" id="logar"
						style=" background-color:#1e317a !important;"
						action="#{loginMB.login}" value="Entrar">
						</h:commandButton>
				</div>

			</h:form>
		</div>
	</div>

</h:body>



</html>

src/main/webapp/register/register.xhtml
<ui:composition template="/WEB-INF/templates/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
	<ui:define name="content">
		<h:outputStylesheet library="css" name="style.css" />
		<div class="container">
			<h3>Cadastro da empresa</h3>
			<h:form>
				<h:panelGrid columns="2">
					<h:outputLabel for="companyName" value="Nome da empresa:" />
					<h:inputText id="companyName" value="#{companyMB.name}" />

					<h:commandButton value="Salvar" icon="ui-icon-star"
						action="#{companyMB.save}" ajax="false">
					</h:commandButton>
				</h:panelGrid>
			</h:form>
			<c:if test="#{not empty companyMB.id}">
				<h:form>
					<h3>Cadastro de usuário da Empresa</h3>
					<h:inputHidden id="companyId" value="#{companyMB.id}" />

					<h:outputLabel for="userName" value="Nome do usuário:" />
					<h:inputText id="userName" value="#{userMB.name}" />

					<h:outputLabel for="userEmail" value="E-mail do usuário:" />
					<h:inputText id="userEmail" value="#{userMB.email}" />

					<h:commandButton value="Salvar" icon="ui-icon-star"
						action="#{userMB.createCustomer}" ajax="false">
					</h:commandButton>
				</h:form>
			</c:if>
		</div>
	</ui:define>
</ui:composition>

src/main/webapp/users/list.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css"></link>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
    <script
        src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
        rel="stylesheet" />
</h:head>
<h:body>
    <div class="container">
        <ui:repeat value="#{userListMB.users}" var="user">
            <div>
                <h3>#{user.email}</h3>
                <div>User: #{user.id} - #{user.email}</div>
                <div>Role: #{user.role.id} - #{user.role.name}</div>
            </div>
        </ui:repeat>
    </div>
</h:body>
</html>